import { asSocietyError, err, ok } from "@ses/domain";
import type { Result, Society, SocietyId, UserId } from "@ses/domain";

import { loadSocietyContext, requireCapability } from "./support";
import type { SocietyDeps } from "./support";

/**
 * Rotate the join code (PRD §3.2: the code is "Regenerable by Admin; optional
 * expiry").
 *
 * The new code is generated by the repository, not here: uniqueness against every
 * other society is a storage concern, and the value object only owns the code's
 * *shape* (see `join-code.ts`). What the domain decides is who may do it.
 *
 * Rotation invalidates the old code immediately, so a leaked code is contained by
 * one admin action — which is why this is audited in the API layer (T050).
 */
export async function regenerateJoinCode(
  deps: SocietyDeps,
  actor: UserId,
  societyId: SocietyId,
): Promise<Result<Society, ReturnType<typeof asSocietyError>>> {
  const loaded = await loadSocietyContext(deps, actor, societyId);
  if (!loaded.ok) return loaded;

  const guard = requireCapability(
    loaded.value.capabilities,
    "canRegenerateJoinCode",
    "Only a society Admin can regenerate the join code.",
  );
  if (!guard.ok) return guard;

  try {
    return ok(await deps.repository.regenerateJoinCode(societyId, actor));
  } catch (error: unknown) {
    return err(asSocietyError(error));
  }
}
